source "https://rubygems.org"

# # use local theme gem for testing
# gem "minimal-mistakes-jekyll", path: "../"
# group :jekyll_plugins do
#   gem 'jekyll-algolia', '~> 1.0'
# end

# gem "wdm", "~> 0.1.0" if Gem.win_platform?
# gem "webrick"

gem "jekyll", "~> 4.2"  # 최신 Jekyll 사용
gem "jekyll-sass-converter", "~> 3.0"  # 최신 Sass 변환기 사용
gem "minimal-mistakes-jekyll"  # Minimal Mistakes 테마 최신 버전